name: Releases

on: 
  push:
    tags:
    - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write      
    steps:
    - run: echo ::set-env name=REPO_NAME::${GITHUB_REPOSITORY#*/}-${GITHUB_SHA:0:7}
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.6
      with:
        type: 'zip'
        filename: '${{env.REPO_NAME}}.zip'
        exclusions: '/.git* .git* README.md'
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: '${{env.REPO_NAME}}.zip'
        allowUpdates: true
