name: Releases

on: 
  push:
    tags:
    - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write      
    steps:
    - name: Set ENV variables
      run: echo "REPO_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_ENV
    - name: test
      run: echo $REPO_NAME
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.6
      with:
        type: 'zip'
        filename: '$REPO_NAME.zip'
        exclusions: '/.git* .git* README.md'
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "$REPO_NAME.zip"
        allowUpdates: true
