name: Releases

on: 
  push:
    tags:
    - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write      
    steps:
    - name: Get repository name
      id: repo-name
      uses: MariachiBear/get-repo-name-action@v1.3.0
      with:
          with-owner: 'false'
          string-case: 'uppercase'
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.6
      env:
          REPO_NAME: ${{ steps.repo-name.outputs.repository-name }}
      with:        
        type: 'zip'
        filename: '${{env.REPO_NAME}}.zip'
        exclusions: '/.git* .git* README.md'
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      env:
          REPO_NAME: ${{ steps.repo-name.outputs.repository-name }}
      with:
        artifacts: '${{env.REPO_NAME}}.zip'
        allowUpdates: true
